# See https://redocly.com/docs/cli/configuration/ for more information.
apis:
  sample@v1: 
    root: openapi/openapi.yaml
  sample@v2: 
    root: openapi/openapi1.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: error
features.openapi:
  requiredPropsFirst: "true"
  theme:
    colors:
      primary:
        main: "#32329f"
  generateCodeSamples:
    languages:  # Array of language config objects; indicates in which languages to generate code samples.
      - lang: curl
      - lang: Node.js
      - lang: JavaScript
      - lang: PHP
      - lang: Python
