openapi: 3.0.2
info:
  title: OpenAPI definition
  version: v0
servers:
- url: https://127.0.0.1:8080
  description: Generated server url
paths:
  "/api/v1/candidates":
    get:
      tags:
      - api-rest-controller
      operationId: fetchCandidates
      parameters:
      - name: skill
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
           application/json::
              schema:
                type: object
          '404':
      description: Not found response
      content:
        text/plain:
          schema:
            title: Weather not found
            type: string
            example: Not found       
components: {}
