openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
  summary: ""
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  "/api/v1/candidates":
    get:
      tags:
      - api-rest-controller
      operationId: fetchCandidates
      parameters:
      - name: skill
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: object
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt
      description: 'note: non-oauth scopes are not defined at the securityScheme level'
