openapi: 3.0.2
info:
  title: OpenAPI definition
  version: v0
servers:
- url: https://localhost:8080
  description: Generated server url
paths:
  "/api/v1/candidates":
    get:
      tags:
      - api-rest-controller
      operationId: fetchCandidates
      summary: sdfds
      parameters:
      - name: skill
        in: query
        required: false
        schema:
          type: string
     responses:
  '200':
    description: OK
  
security: 
  - OAuth: []                
components: {}
